### ISSUE TITLE
Probe should use Assimilator for gather, not Refinery

### ISSUE THREAD

**Issue by Venorcis** [OpenBW/BWAPI4J#10]

**Comment by adakitesystems** [comment]
Nice catch. The proposed fix from @Bytekeeper's commit https://github.com/Bytekeeper/BWAPI4J/commit/d16ba178778722dd1cfd98a27db4de68a6ee8cc8 will most likely be used.

This issue can be considered closed but will remain open until the fix is merged into the main branch.

**Comment by dgant** [comment]
I believe if you Mind Control an SCV, it can gather from your Assimilator. It may also be possible with teammates. If so, this poses an unnecessary restriction.

**Comment by adakitesystems** [comment]
Very good point, @dgant. I did not think of this. Correct me if I'm wrong, but I believe @Bytekeeper has either addressed this or *almost* addressed this in his proposed "Worker" commit by using the superclass `GasMiningFacility` in the method signatures instead of a specific subclass.

Commit: https://github.com/Bytekeeper/BWAPI4J/commit/3807f8e18e09f5d557be486c0cb04517f376dbd3#diff-117b390fdab6b35d86db9d8c834ae8d4R72

I think the problem still lies with `public abstract class Worker<R extends GasMiningFacility> extends MobileUnit`. I am not sure `Worker` should include a generic type for its definition. Maybe the class should remove its generic parameter and be defined as `public abstract class Worker`. Then, `public boolean gather(GasMiningFacility gasMiningFacility)` can be used instead of the current `public boolean gather(R gasMiningFacility)` where `R` will be hardcoded during `Worker` definitions.

**Comment by adakitesystems** [comment]
Merged.
