### ISSUE TITLE
No way to load units in bunker right now

### ISSUE THREAD

**Issue by Venorcis** [OpenBW/BWAPI4J#11]
Neither Bunker nor MoveableUnit seems to some kind of load (nor unload) action. It would also be useful to get the loaded units from it (but this is a TODO in the code already).

P.S. Transporter should probably be an abstract class?

**Comment by adakitesystems** [comment]
Thanks for the bug report. I'll look into this.

I like the idea of `Transporter` being an abstract class and also using it as a superclass for any unit/building that can load/unload units. E.g. `Bunker extends Transporter`. Perhaps the `Transporter` name is not well fit when referring to a unit that can load/unload units. This class should be renamed, IMO.

**Comment by dgant** [comment]
Commenting very hastily without inspecting whether it's already feasible:
It should be both possible to order all of the following:
- Unit clicks transport
- Transport clicks unit
- Transport unloads at position
- Transport unloads specific unit (clicking portrait)
- Transport unloads all units (targeting self)
as these have different behaviors in-game. For example, with reaver/shuttle you most frequently want to select the reaver and click on the shuttle, because that causes the reaver to board without causing the shuttle to slow down. With dropping off units, IIRC telling the shuttle to unload and targeting itself causes the units to fall out as fast as possible without slowing down the shuttle.

(My not-so-secret agenda is for BWAPI4J to stop trying to anticipate what orders developers will want to issue, because there's a lot of little mechanics like these)

**Comment by adakitesystems** [comment]
I agree with a lot of points made by @dgant in the above post.

> (My not-so-secret agenda is for BWAPI4J to not be preferential about what commands developers can issue, because there's a lot of little mechanics like these 😄 ❤️)

I agree and disagree with this. I wrote a few hundred words outlining some valid arguments both for and against a restrictive-like approach for BWAPI4J but decided to scrap it. A simplified version of my opinion on this matter is that a restrictive API is better than allowing a developer to call whichever function they want. I do agree that some novelties or functionality may be overlooked. But those issues *should* be easily rectified.

This topic definitely deserves a lengthly discussion.

**Comment by adakitesystems** [comment]
You should be able to use the method `PlayerUnit.rightClick(Unit)` where the `PlayerUnit` is a marine and the `Unit` is the bunker.

But you are correct. The load command should be added to the `Bunker` class. I will also look into refactoring the `Transporter` class to be an interface or abstract class of some kind.

**Comment by adakitesystems** [comment]
Added commit https://github.com/OpenBW/BWAPI4J/commit/1cf699da65d521679b781830b355d0237d8ec046

**Comment by adakitesystems** [comment]
Before this issue is closed, I think `Loadable` needs to be refactored further. A better name might be `Loader`. The difference becomes apparent when talking about a `Marine` and a `Bunker`. Marines can be loaded (Loadable) into a Bunker (Loader). With these separate interfaces, the "load/unload/unloadAll" might be easier to implement and use.

**Comment by adakitesystems** [comment]
I have reconsidered refactoring `Loadable`. If it is needed, it will be done at a later time.

**Comment by Venorcis** [comment]
Getting the units that are loaded into a Transporter (or Bunker) still seems impossible though
