### ISSUE TITLE
Lacking support for gamemodes with more than 2 players

### ISSUE THREAD

**Issue by Jabbo16** [OpenBW/BWAPI4J#40]
Hi, I noticed that currently there is no support for handling gamemodes with more than 2 players. One example is FFA where there are multiple enemies.

`InteractionHandler` lacks the methods `allies()` and `enemies()` present in BWAPI `Game` class.

**Comment by adakitesystems** [comment]
Thanks for the bug report. I have implemented and tested the requested methods:
```java
public List<Player> allies()
public List<Player> enemies()
```
Please re-open if there is still an issue.

**Note:** These are pure JNI methods with no caching. I am undecided on whether or not these should be cached since allies and enemies can dynamically change throughout the game and may not require caching optimization due to their invocation rarity. Feel free to protest this decision.

**Comment by Jabbo16** [comment]
Thanks for the fix.

I only use them one time at the start of the game to build my own data structures regarding players so atleast for me its fine if they are not cached.

**Comment by adakitesystems** [comment]
@Bytekeeper, that's a valid argument and is also a design decision that can be discussed which is not just related to the allies and enemies methods: Do we cache almost every value possible every frame or only the most important values? I do not know if C++ pushing to Java every frame is faster/slower/equal (or by how much) compared to Java requesting from C++ less often (i.e. not every frame). If someone has a definitive answer, I'm all ears. Otherwise, we may need to profile it somehow. On the other hand, I suppose we can cache everything and then trim it down later if required.
