### ISSUE TITLE
Could not get the Bridge file for vanilla BW on windows

### ISSUE THREAD

**Issue by youngmoon01** [OpenBW/BWAPI4J#72]
This would be a tedious question, but I am not getting the bridge file(.dll) for vanilla BW on windows.

I have successfully got it for OpenBW in linux, and compiled the bot and could run the test bot in openbw.

But for the vaniila BW, strangely, gradle task finished 'successfully' but I can't find the bridge file at the build directory neither at the path below where I could have found the bridge file for openBW.
     BWAPI4J/BWAPI4JBridge/Release
     (even directory is not created)

Could anyone tell me am I missing something?

**Comment by Jabbo16** [comment]
Did you compile the Bridge by running `./gradlew buildVanillaBridgeForWindows` ?

Other option its to download Appveyor's artifacts which already include the bridge.

**Comment by youngmoon01** [comment]
@Jabbo16 
Yes I tried gradlew.bat buildVanillaBridgeForWindows and it didn't produce the bridge file.

Thanks to your comment, I could find the jar file which includes bridge file, and could successfully run test bot with BWAPI launcher in windows environment! :)

**Comment by adakitesystems** [comment]
Hi, @youngmoon01!

I know this issue is closed but maybe I could offer some information that might be of help if you still would like to compile the bridge yourself. The build system is unfortunately pretty fragile with lack of proper error/exit reporting but luckily still powerful. 

The following set of commands work on my system. Note: you may need to run the `gradlew.bat` commands with the default Windows command prompt or use IntelliJ's Gradle plugin because the Gradle tasks read Windows environment variables. I have had issues building the bridge with Git bash for Windows. You will also need to have Visual Studio 2017 installed before running the scripts.

```
git clone https://github.com/OpenBW/BWAPI4J.git
cd BWAPI4J/
git submodule update --init --recursive
cd BWAPI4J/
gradlew.bat clean build buildVanillaBridgeForWindows
gradlew.bat shadowJar
```
Details:

| Command | Description |
|-|-|
| `git clone https://github.com/OpenBW/BWAPI4J.git` | Clones the repo |
| `cd BWAPI4J/` | Changes current working directory to the root project directory |
| `git submodule update --init --recursive` | Downloads/Updates project dependencies into `BWAPI4J/BWAPI4JBridge/externals/` |
| `cd BWAPI4J/` | Changes cwd to the main Java project directory |
| `gradlew.bat clean build buildVanillaBridgeForWindows` | Builds both Java and C++ projects |
| `gradlew.bat shadowJar` | Packages the Java and C++ binaries into `BWAPI4J/BWAPI4J/build/libs/BWAPI4J-0.8.2b.jar` |

**Comment by HaebeomLee** [comment]
@adakitesystems 
Thank you for you detailed instruction to build the bridge file!
But the steps doesn't seem to work for my machine :(
I have run exactly same command in same order, but the bridge file is not built.
I'm not sure what is the problem. I have visual studio 2017, and there was no 'failure' message during those steps..

**Comment by youngmoon01** [comment]
@adakitesystems 
Thank you for you detailed instruction to build the bridge file!
But the steps doesn't seem to work for my machine :(
I have run exactly same command in same order, but the bridge file is not built.
I'm not sure what is the problem. I have visual studio 2017, and there was no 'failure' message during those steps..

**Comment by adakitesystems** [comment]
> [...] there was no 'failure' message during those steps..

Yes, the build system really needs better error reporting. Either it works or it doesn't. At the moment, all we can do is guess what is going wrong.

Try the following if you don't mind:

1. Verify that you are using the `develop` branch of `https://github.com/OpenBW/BWAPI4J/`.
2. Verify that the Gradle task `generateVsDevCmdBatch` does its job successfully by checking if the task generates the file `BWAPI4J/BWAPI4JBridge/VsDevCmd.bat`. If this file is missing, the scripts will not be able to build any C++ binary. You can manually invoke this single task with `gradlew.bat generateVsDevCmdBatch`. 

My generated batch file looks like this:
```
@echo Setting up VS2017 Development Environment...

IF EXIST "C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" (
"C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
)
```

**Comment by youngmoon01** [comment]
@adakitesystems 
1. Yes it is 'develop' branch(0.8.2b version)
2. The file exists and it has same string as yours.

Still not sure what is the problem..

**Comment by adakitesystems** [comment]
@youngmoon01 
Strange. At least that file is generated properly. Sorry for your inconvenience.

Can you verify that the "true" file exists on your system? E.g. `C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat`? Since the generated batch file merely calls the true file on the system.

At this time, I don't have any more ideas of what could be the problem. Would you be able to post an output log of the Gradle task `buildVanillaBridgeForWindows` here or compare it yourself against our AppVeyor's log of `0.8.2b build 113` which located at https://ci.appveyor.com/project/adakitesystems/bwapi4j/build/0.8.2b%20build%20113 ? I know there is a lot going on in the log, but narrowing the comparison to the following sections may help:
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 9/4/2018 6:29:12 PM.
Project "C:\projects\bwapi4j\BWAPI4JBridge\build_vanilla_windows\BWAPI4JBridge.sln" on node 1 (default targets).
```

```
     Creating library C:/projects/bwapi4j/BWAPI4JBridge/Release/BWAPI4JBridge.lib and object C:/projects/bwapi4j/BWAPI4JBridge/Release/BWAPI4JBridge.exp
  Generating code
  Finished generating code
  BWAPI4JBridge.vcxproj -> C:\projects\bwapi4j\BWAPI4JBridge\Release\BWAPI4JBridge.dll
```

```
Done Building Project "C:\projects\bwapi4j\BWAPI4JBridge\build_vanilla_windows\BWAPI4JBridge.sln" (default targets).
Build succeeded.
    0 Warning(s)
    0 Error(s)
```

**Comment by adakitesystems** [comment]
Also, please verify you have CMake installed. I am currently running `cmake version 3.11.4` on Windows.
